development:
  adapter: postgresql
  database: jasmine_dragon_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: jasmine_dragon_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: jasmine_dragon_production
  pool: 5
  timeout: 5000